### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by levin950825** [zxiaozhou/anyi-cloud-vue#43]
userApi、groupApi、expressionApi、orgTreeApi  
是否可以通过返回内容配置字典的方式动态控制字段而不是局限内置的三个字段 
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/13896536/196864883-196f6259-20b2-42a8-8b2d-d38600c8c1c0.png">

比如 
{
dict:[
{"username":"用户名","xxx":"xxxx"}
],
pageList
}

**Comment by zxiaozhou** [comment]
@levin950825 新版本已经支持
